language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-cc' ]; then cd .. && eval "mv $currentfolder generator-cc" && cd generator-cc; fi

